<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTUB3ndA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTUB3ndA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTUB3ndA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTUB3ndA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTUB3ndA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TUB3ndA',
    'container.build_id' => 'f22f980c',
    'container.build_time' => 1565769689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTUB3ndA');
